# Generated by Django 3.2.9 on 2021-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsonRest', '0002_alter_jsondata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='data',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
